export const LOAD_PLAYERS_DATA_SUCCESS = 'LOAD_PLAYERS_DATA_SUCCESS';
export const TOGGLE_PLAYER_VOTE_COMPLETE = 'TOGGLE_PLAYER_VOTE_COMPLETE';
export const END_VOTING_COMPLETE = 'END_VOTING_COMPLETE';
export const TOGGLE_USER_MODE_COMPLETE = 'TOGGLE_USER_MODE_COMPLETE';
export const TOGGLE_ADMIN_MODE_COMPLETE = 'TOGGLE_ADMIN_MODE_COMPLETE';
export const SELECT_REGION_COMPLETE = 'SELECT_REGION_COMPLETE';
export const AJAX_CALL_SUCCESS = 'AJAX_CALL_SUCCESS';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
